# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 07:36
from __future__ import unicode_literals

from django.db import migrations

def add_site_data(apps,schema_editor):
    Site = apps.get_model('sites','Site')
    new_domain = 'site.django-unleashed.com'
    new_name = 'Startup Organizer'
    site_id = getattr(settings, 'SITE_ID',1)

def remove_site_data(apps, schema_editor):

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
