# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_startup_founded_date'),
    ]

    operations = [
    ]
